### ISSUE TITLE
PersistenceService work in Linux

### ISSUE THREAD

**Issue by ScottLilly** [ScottLilly/MegaCorpClash#275]
Backslash needs to be environment-specific on lines 10, 11

Path.Combine()

**Comment by TheyCallMeTojo** [comment]
After letting the game run almost 24 hours and then trying to restart the game, I ran into another problem. The database was 'missing'.

`    static CompanyRepository()
    {
        Directory.CreateDirectory(@".\Data");

        _database = new LiteDatabase(@".\Data\Companies.db");
    }`

This creates a weird '/\Data/\Companies.db' file instead of creating the directory then the db. 

So the game runs the first time only. Upon subsequent executions you get a file not found error for the db. What's odd is there's no exceptions being thrown while running the first time. You'd think it'd crash trying to write to a db that isn't there. Odd.
