### ISSUE TITLE
Broken App & Undesired behavior after Broadcaster name change.

### ISSUE THREAD

**Issue by TheyCallMeTojo** [ScottLilly/MegaCorpClash#290]
I started using MCC using the Twitch name "TheyCallMeTojo". I changed this name to "CodeWithTojo". MCC will execute with no errors and proceed to run until stopped. However, commands do not trigger MCC. MCC does not deliver the "Starting" and "Stopping" messages as it should. 

If I change the appsettings.json to update my username and execute the application again, same results. MCC actually rewrites the appsettings.json using my OLD username after each execution. 

Here is a gif showing how it reverts back to the old appsettings.json. 

Don't worry, I revoked that token already. 
![Animation](https://user-images.githubusercontent.com/5115817/204116725-c0e3f4d1-9f3f-48a2-aa39-a6cdadc09d88.gif)

**Comment by ScottLilly** [comment]
I suspect the commands didn't trigger (after updating the channel name) because the auth token would also need to be changed to the one for the "CodeWithTojo" account.

The name probably changed back to "TheyCallMeTojo" because you rebuilt the app, and the "build" process copied the project's appsettings.json into the debug/net6.0 directory. I'll check if that's set to "Copy always" or "Copy if newer".

Please let me know if those resolve the issue.
